services:
  traefik:
    image: traefik:v3
    restart: unless-stopped
    env_file: .env
    environment:
      - DOCKER_API_VERSION=${DOCKER_API_VERSION:-1.44}
    command:
      - --log.level=INFO
      - --accesslog=true
      - --api.dashboard=false
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/dynamic-dev.yml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik/dynamic-dev.yml:/etc/traefik/dynamic-dev.yml:ro
    networks:
      - v2ray-hub-dev-net

  app:
    image: oven/bun:1-alpine
    restart: unless-stopped
    env_file: .env
    stdin_open: true
    tty: true
    working_dir: /app
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    depends_on:
      mongo:
        condition: service_healthy
      traefik:
        condition: service_started
    environment:
      - NODE_ENV=development
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
      - NUXT_PORT=3000
      - NUXT_HOST=0.0.0.0
      - NUXT_APP_SECRET=${APP_SECRET:-}
      - NUXT_ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET:-}
      - NUXT_MONGO_URI=${MONGO_URL:-}
      - PORT=3000
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongo:27017/v2ray-hub
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}
    ports:
      - "3000:3000"
    networks:
      - v2ray-hub-dev-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.xsubstore-dev.rule=Host(`${DEV_DOMAIN:-localhost}`)
      - traefik.http.routers.xsubstore-dev.entrypoints=websecure
      - traefik.http.routers.xsubstore-dev.tls=true
      - traefik.http.services.xsubstore-dev.loadbalancer.server.port=3000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    tmpfs:
      - /app/.nuxt
      - /app/.nitro

  mongo:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - /tmp/x-sub-store/dev/mongo-data:/data/db
    networks:
      - v2ray-hub-dev-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  v2ray-hub-dev-net:
