name: x-sub-store-dev

services:
  app:
    container_name: ss-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: x-sub-store-app:dev
    restart: unless-stopped
    env_file: .env
    command: sh /app/scripts/dev-start.sh
    stdin_open: true
    tty: true
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
      - NUXT_PORT=3000
      - NUXT_HOST=0.0.0.0
      - NUXT_APP_SECRET=${APP_SECRET:-}
      - NUXT_ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET:-}
      - NUXT_MONGO_URI=${MONGO_URL:-}
      - PORT=3000
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongo:27017/v2ray-hub
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-false}
    ports:
      - "3000:3000"
    networks:
      - v2ray-hub-dev-net
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - app_nuxt:/app/.nuxt
      - app_nitro:/app/.nitro
      - app_bun_cache:/root/.bun/install/cache
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 45s

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - v2ray-hub-dev-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    depends_on:
      app:
        condition: service_healthy
    environment:
      - DOMAIN=${DEV_DOMAIN:-localhost}
    networks:
      - v2ray-hub-dev-net
    volumes:
      - ./nginx/templates-dev/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/cert-local:/etc/nginx/cert-local:ro
    healthcheck:
      test: ["CMD-SHELL", "nginx -t -q || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:
    name: x-sub-store-dev-mongo-data
  app_node_modules:
    name: x-sub-store-dev-node-modules
  app_nuxt:
    name: x-sub-store-dev-nuxt-cache
  app_nitro:
    name: x-sub-store-dev-nitro-cache
  app_bun_cache:
    name: x-sub-store-dev-bun-cache

networks:
  v2ray-hub-dev-net:
